### ISSUE TITLE
Error in writing output file

### ISSUE THREAD

**Issue by FrancescoVit** [Lagkouvardos/Rhea#13]
Hi all! Really nice and useful package, thanks.

Spotted an error in Correlations.R, line 485
`prefix = paste(strsplit(input_filename,"[.]")[[1]][1],sep="_")`
should be replaced with
`prefix = paste(strsplit(input_file,"[.]")[[1]][1],sep="_")`
as the variable "input_filename" is not defined, but variable "input_file" is.

Again, great work!
Francesco.

**Comment by Lagkouvardos** [comment]
Thanks very much Francesco for catching this.  We fixed it!
All the best too you,
Ilias
