### ISSUE TITLE
Object 'cl_pam' not found

### ISSUE THREAD

**Issue by thh32** [Lagkouvardos/Rhea#14]
Hi having an issue where in the 'Beta-Diversity.R' script and the 'De-novo-Clustering.R' script when using command `pam(as.dist(unifract_dist_comp), k, diss=TRUE)$clustering`.

I keep getting the error:
Error in pam(as.dist(unifract_dist_comp), k, diss = TRUE) : 
  object 'cl_pam' not found

Any idea what is causing this error?

**Comment by SandraReitmeier** [comment]
Hi,

could be that something with the package installation went wrong. Could you check again if the package 'cluster' was installed properly? Try 

install.packages('cluster')
library('cluster')

If you are still getting the error send me an e-mail and we will figure out why it fails
sandra.fischer@tum.de

**Comment by thh32** [comment]
Thanks for the help, that seems to have sorted it out
