### ISSUE TITLE
Over-Time-Serial-Comparisons.R

### ISSUE THREAD

**Issue by wholeGenomeSequencingAnalysisPipeline** [Lagkouvardos/Rhea#18]
Over-Time-Serial-Comparisons, used to assess the microbial shift over 2 or more various time points (i.e. paired comparisons). While Serial-Group-Comparisons.R compare between various groups ( non-paired testing). In case of having 2 or more interventions on the microbiome (e.g. antibiotics A, B, C), and you have a before and after sample, how would use make use of both paired testing (before and after AB) and compare those changes accross the various antibiotics.

Thanks alot

**Comment by Lagkouvardos** [comment]
You need to manually create separate input files for every category (e.g. for two treatments with two timepoints you need two files properly formatted for overtime analysis:1) treatmentA; 2) treatmentB. If you want to test both OTUs and Taxa you need 4 files). Then you run the overtime tests for each treatment and collect the p-values comparing before and after. Then run the serial group comparison for all over the compound category Treatment-Time. You keep the boxplots outputs of treatmentA-Before, treatmentA-After, treatmentB-Before, treatmentB-After and the p-values for treatmentA-before to treatmentB-before and treatmentB-after to treatmentB-after, and replace the p-values of before-after comparisons with those from the overtime paired test.
