### ISSUE TITLE
Error running "Serial-Group-Comparison.R" with provided example data

### ISSUE THREAD

**Issue by telatin** [Lagkouvardos/Rhea#19]
The previous step worked fine, but running Serial-Group-Comparison.R I get:
```
Error in Summary.factor(c(3L, 3L, 1L, 1L, 3L, 3L, 3L, 1L, 3L, 1L, 1L,  : 
  ‘sum’ not meaningful for factors
Calls: xtabs -> tapply -> lapply -> Summary.factor
```
This is triggered by 
`test_table <- xtabs(my_test_vector ~ independent_variable)`

I presume that can be fixed by `dependant_variables_start <- 5` but I wanted to understand if the previous step did produce a malformed table (?)

**Comment by Lagkouvardos** [comment]
Hi, did you change anything else in the values of the variables or the script itself?
It runs fine with me.

**Comment by telatin** [comment]
Thanks for the feedback. I didnt change anything intentionally, so I'll redownload and re-check
