### ISSUE TITLE
Setting path for installation file

### ISSUE THREAD

**Issue by ghost** [Lagkouvardos/Rhea#24]
https://github.com/Lagkouvardos/Rhea/blob/bea21745fcbc62a5dcfa93ce2333356865c1d4ca/install_packages.R#L14

Regarding the referenced line above I was thinking if 
```
setwd(getwd())
```
would also work?! In that case users wont need to set up the file of the directory.

**Comment by Lagkouvardos** [comment]
Unfortunately not. getwd() will get the active working directory at the time not the directory of the script.
Therefore setwd(getwd()) wont do anything

**Comment by ghost** [comment]
ok. It seemed that it have worked for some scripts, that is why I came up with the suggestion.
